package com.csub.exception;

import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
public enum ErrorList {
    USER_NOT_FOUND(1001, HttpStatus.NOT_FOUND),
    SUBSCRIPTION_NOT_FOUND(1002, HttpStatus.NOT_FOUND),
    MANAGER_NOT_FOUND(1003, HttpStatus.NOT_FOUND),
    USER_ALREADY_EXISTS(1004, HttpStatus.NOT_FOUND),
    SUBSCRIPTION_ALREADY_EXISTS(1005, HttpStatus.NOT_MODIFIED),
    MANAGER_ALREADY_EXISTS(1006, HttpStatus.NOT_MODIFIED),
    USER_NOT_VALID(1007, HttpStatus.BAD_REQUEST),
    SUBSCRIPTION_NOT_VALID(1008, HttpStatus.BAD_REQUEST),
    MANAGER_NOT_VALID(1009, HttpStatus.BAD_REQUEST),
    USER_NOT_AUTHORIZED(1010, HttpStatus.UNAUTHORIZED),
    SUBSCRIPTION_NOT_AUTHORIZED(1011, HttpStatus.UNAUTHORIZED),
    MANAGER_NOT_AUTHORIZED(1012, HttpStatus.UNAUTHORIZED),
    USER_NOT_LOGGED_IN(1013, HttpStatus.UNAUTHORIZED),
    SUBSCRIPTION_NOT_LOGGED_IN(1014, HttpStatus.UNAUTHORIZED),
    MANAGER_NOT_LOGGED_IN(1015, HttpStatus.UNAUTHORIZED),
    USER_NOT_CREATED(1016, HttpStatus.NOT_MODIFIED),
    SUBSCRIPTION_NOT_CREATED(1017, HttpStatus.NOT_MODIFIED),
    MANAGER_NOT_CREATED(1018, HttpStatus.NOT_MODIFIED),

    VALIDATION_ERROR(1019, HttpStatus.BAD_REQUEST),

    CAR_NOT_FOUND(1020, HttpStatus.NOT_FOUND),

    SERVER_ERROR(2000, HttpStatus.INTERNAL_SERVER_ERROR),
    IMAGE_SAVE_ERROR(2001, HttpStatus.INTERNAL_SERVER_ERROR),
    IMAGE_GET_ERROR(2002, HttpStatus.INTERNAL_SERVER_ERROR),
    CAR_STATUS_NOT_FOUND(3003, HttpStatus.NOT_FOUND),
    SUBSCRIPTION_STATUS_NOT_FOUND(3004, HttpStatus.NOT_FOUND),
    USER_VERIFICATION_ERROR(10023, HttpStatus.BAD_REQUEST),
    EMAIL_NOT_SENT(5004, HttpStatus.INTERNAL_SERVER_ERROR),
    PAYMENT_FAILED(5005, HttpStatus.INTERNAL_SERVER_ERROR),
    USER_ALREADY_SUBSCRIBED(4001, HttpStatus.BAD_REQUEST),
    CAR_ALREADY_SUBSCRIBED(4002, HttpStatus.BAD_REQUEST),
    CAR_NOT_CREATED(1030, HttpStatus.INTERNAL_SERVER_ERROR),
    GENERATING_REPORT_FAILED(6000, HttpStatus.INTERNAL_SERVER_ERROR),
    USER_BLOCKED(4005, HttpStatus.FORBIDDEN);


    private final int code;

    private final HttpStatus status;

    public int getErrorCode() {
        return code;
    }

    public HttpStatus getHttpStatus() {
        return status;
    }

}
